# Generated by Django 2.2.5 on 2019-10-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Anwar Ruff', max_length=255),
            preserve_default=False,
        ),
    ]
