# Generated by Django 2.2.6 on 2019-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Anwar Ruff', max_length=255, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
