# Generated by Django 2.2.6 on 2019-10-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_experimenter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experimenter',
            new_name='Researcher',
        ),
    ]
